language: python

python:
  - "2.7"

env:
  - VERSION="8.0" EXCLUDE="partner_address_street3"
  - VERSION="8.0" INCLUDE="partner_address_street3"

virtualenv:
  system_site_packages: true

install:
  - pip install requests
  - pip install unicodecsv
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - $HOME/maintainer-quality-tools/travis/travis_install_nightly ${VERSION}

script:
  - travis_run_flake8
  - travis_run_tests ${VERSION}

after_success:
  coveralls
