[project]
name = "odoo-addons-oca-partner-contact"
version = "17.0.20231203.0"
dependencies = [
    "odoo-addon-partner_contact_personal_information_page>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
